### ISSUE TITLE
Update from tkcode to chlorophyll

### ISSUE THREAD

**Issue by Moosems** [ayuvius/WhirlEdit#10]

**Comment by whmsft** [comment]
Yes.. I think, I must change.. 

But I haven't yet because I am, these days not really available with my laptop.. 
So I believe by Tomorrow 5pm GMT or by Tuesday 5pm GMT, I will get this updated and also,

I am not actually making any substantial updates to WhirlEdit, however I just have started another editor "Thee" based on the principles of https://github.com/not-nef/txt2

**Comment by whmsft** [comment]
The main problem that I have is just "availability".

I am unavailable completely on weekends..
 And on weekdays I have school and self-studies but I still try to make the most out of the time available to me..

**Comment by Moosems** [comment]
> Yes.. I think, I must change..
> 
> But I haven't yet because I am, these days not really available with my laptop.. So I believe by Tomorrow 5pm GMT or by Tuesday 5pm GMT, I will get this updated and also,
> 
> I am not actually making any substantial updates to WhirlEdit, however I just have started another editor "Thee" based on the principles of https://github.com/not-nef/txt2

Where's the repo?

**Comment by whmsft** [comment]
It's sitting on my laptop rn.. But will update to github as soon as it gets any good

**Comment by whmsft** [comment]
@Moosems I believe that switching from `tkcode` to `chlorophyll` will be really major kind of thing...

It will make me rewrite major parts of the editor and first of all, `chlorophyll` uses `toml` for extensions and that will make me rewrite all the colorschemes I made earlier.

So, This will not be fixed 

Foot note: as `tkcode` has become obsolete, `whirledit` too is obsolete...
